// <auto-generated>
// This code is generated by csbindgen.
// DON'T CHANGE THIS DIRECTLY.
// </auto-generated>
#pragma warning disable CS8500
#pragma warning disable CS8981
using System;
using System.Runtime.InteropServices;


namespace Primrose.Graphics.Taffy.Native
{
    internal static unsafe partial class NativeMethods
    {
#if PRIMROSE_IOS
        const string __DllName = "__Internal";
#else
        const string __DllName = "taffy";
#endif
        



        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetDisplay", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDisplay TaffyStyle_GetDisplay(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetDisplay", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetDisplay(TaffyStyle* raw_style, TaffyDisplay value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPosition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyPosition TaffyStyle_GetPosition(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPosition", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPosition(TaffyStyle* raw_style, TaffyPosition value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetOverflowX", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyOverflow TaffyStyle_GetOverflowX(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetOverflowX", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetOverflowX(TaffyStyle* raw_style, TaffyOverflow value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetOverflowY", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyOverflow TaffyStyle_GetOverflowY(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetOverflowY", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetOverflowY(TaffyStyle* raw_style, TaffyOverflow value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAlignContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetAlignContent(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAlignItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetAlignItems(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAlignSelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetAlignSelf(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetJustifyContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetJustifyContent(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetJustifyItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetJustifyItems(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetJustifySelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern int TaffyStyle_GetJustifySelf(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAlignContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAlignContent(TaffyStyle* raw_style, TaffyAlignContent value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAlignItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAlignItems(TaffyStyle* raw_style, TaffyAlignItems value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAlignSelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAlignSelf(TaffyStyle* raw_style, TaffyAlignItems value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetJustifyContent", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetJustifyContent(TaffyStyle* raw_style, TaffyAlignContent value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetJustifyItems", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetJustifyItems(TaffyStyle* raw_style, TaffyAlignItems value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetJustifySelf", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetJustifySelf(TaffyStyle* raw_style, TaffyAlignItems value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexDirection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyFlexDirection TaffyStyle_GetFlexDirection(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexDirection", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexDirection(TaffyStyle* raw_style, TaffyFlexDirection value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexWrap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyFlexWrap TaffyStyle_GetFlexWrap(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexWrap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexWrap(TaffyStyle* raw_style, TaffyFlexWrap value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetGridAutoFlow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyGridAutoFlow TaffyStyle_GetGridAutoFlow(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetGridAutoFlow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetGridAutoFlow(TaffyStyle* raw_style, TaffyGridAutoFlow value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetWidth(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetWidth(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetHeight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetHeight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMinWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMinWidth(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMinWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMinWidth(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMinHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMinHeight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMinHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMinHeight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMaxWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMaxWidth(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMaxWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMaxWidth(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMaxHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMaxHeight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMaxHeight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMaxHeight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetTop(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetTop(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetBottom(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetBottom(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetLeft(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetInsetRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetInsetRight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetLeft(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetInsetRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetInsetRight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginTop(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginTop(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginBottom(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginBottom(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginLeft(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetMarginRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetMarginRight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginLeft(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMarginRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMarginRight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingTop(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingTop(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingBottom(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingBottom(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingLeft(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetPaddingRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetPaddingRight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingLeft(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetPaddingRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetPaddingRight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderTop(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderTop", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderTop(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderBottom(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderBottom", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderBottom(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderLeft(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetBorderRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetBorderRight(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderLeft", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderLeft(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetBorderRight", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetBorderRight(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetColumnGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetColumnGap(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetColumnGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetColumnGap(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetRowGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetRowGap(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetRowGap", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetRowGap(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetAspectRatio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetAspectRatio(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetAspectRatio", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetAspectRatio(TaffyStyle* raw_style, float value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetScrollbarWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetScrollbarWidth(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetScrollbarWidth", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetScrollbarWidth(TaffyStyle* raw_style, float value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexBasis", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyDimension TaffyStyle_GetFlexBasis(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexBasis", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexBasis(TaffyStyle* raw_style, float value, TaffyUnit unit);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexGrow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetFlexGrow(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexGrow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexGrow(TaffyStyle* raw_style, float value);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetFlexShrink", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern float TaffyStyle_GetFlexShrink(TaffyStyle* raw_style);

        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetFlexShrink", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetFlexShrink(TaffyStyle* raw_style, float value);

        /// <summary>Function to set all the value of margin</summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetMargin", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetMargin(TaffyStyle* raw_style, TaffyEdge edge, TaffyDimension value);

        /// <summary>Get grid item's column placement</summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetGridColumn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyGridPlacement TaffyStyle_GetGridColumn(TaffyStyle* raw_style);

        /// <summary>Set grid item's column placement</summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetGridColumn", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetGridColumn(TaffyStyle* raw_style, TaffyGridPlacement placement);

        /// <summary>Get grid item's row placement</summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_GetGridRow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyGridPlacement TaffyStyle_GetGridRow(TaffyStyle* raw_style);

        /// <summary>Set grid item's row placement</summary>
        [DllImport(__DllName, EntryPoint = "TaffyStyle_SetGridRow", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyStyle_SetGridRow(TaffyStyle* raw_style, TaffyGridPlacement placement);

        /// <summary>Create a TaffyTree instance</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_New", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyTree* TaffyTree_New();

        /// <summary>Free a TaffyTree instance</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_Free", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_Free(TaffyTree* raw_tree);

        /// <summary>Create a new Node in the TaffyTree. Returns a NodeId handle to the node.</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_ComputeLayout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_ComputeLayout(TaffyTree* raw_tree, TaffyNodeId node_id, float available_width, float available_height);

        /// <summary>Create a new Node in the TaffyTree. Returns a NodeId handle to the node.</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_PrintTree", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_PrintTree(TaffyTree* raw_tree, TaffyNodeId node_id);

        /// <summary>Create a new Node in the TaffyTree. Returns a NodeId handle to the node.</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_NewNode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyResult TaffyTree_NewNode(TaffyTree* raw_tree);

        /// <summary>Remove and Free a Node within a TaffyTree</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_RemoveNode", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_RemoveNode(TaffyTree* raw_tree, TaffyNodeId node_id);

        /// <summary>Remove and Free a Node within a TaffyTree</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_AppendChild", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_AppendChild(TaffyTree* raw_tree, TaffyNodeId parent_node_id, TaffyNodeId child_node_id);

        /// <summary>Create a new Node in the TaffyTree. Returns a NodeId handle to the node.</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_GetStyleMut", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyResult TaffyTree_GetStyleMut(TaffyTree* raw_tree, TaffyNodeId node_id);

        /// <summary>Create a new Node in the TaffyTree. Returns a NodeId handle to the node.</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_SetNodeContext", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyReturnCode TaffyTree_SetNodeContext(TaffyTree* raw_tree, TaffyNodeId node_id, delegate* unmanaged[Cdecl]<TaffyMeasureMode, float, TaffyMeasureMode, float, void*, TaffySize> measure_function, void* context);

        /// <summary>Create a new Node in the TaffyTree. Returns a NodeId handle to the node.</summary>
        [DllImport(__DllName, EntryPoint = "TaffyTree_GetLayout", CallingConvention = CallingConvention.Cdecl, ExactSpelling = true)]
        public static extern TaffyResult TaffyTree_GetLayout(TaffyTree* raw_tree, TaffyNodeId node_id);


    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaffyStyle
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaffyTree
    {
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaffyNodeId
    {
        public ulong Item1;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaffySize
    {
        public float width;
        public float height;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaffyDimension
    {
        public float value;
        public TaffyUnit unit;
    }

    [StructLayout(LayoutKind.Sequential)]
    internal unsafe partial struct TaffyGridPlacement
    {
        public short start;
        public short end;
        public ushort span;
    }


    internal enum TaffyDisplay : uint
    {
        Block,
        Flex,
        Grid,
        None,
    }

    internal enum TaffyPosition : uint
    {
        Relative,
        Absolute,
    }

    internal enum TaffyOverflow : uint
    {
        Visible,
        Clip,
        Hidden,
        Scroll,
    }

    internal enum TaffyAlignItems : uint
    {
        Normal,
        Start,
        End,
        FlexStart,
        FlexEnd,
        Center,
        Baseline,
        Stretch,
    }

    internal enum TaffyAlignContent : uint
    {
        Normal,
        Start,
        End,
        FlexStart,
        FlexEnd,
        Center,
        Stretch,
        SpaceBetween,
        SpaceEvenly,
        SpaceAround,
    }

    internal enum TaffyFlexWrap : uint
    {
        NoWrap,
        Wrap,
        WrapReverse,
    }

    internal enum TaffyFlexDirection : uint
    {
        Row,
        Column,
        RowReverse,
        ColumnReverse,
    }

    internal enum TaffyGridAutoFlow : uint
    {
        Row,
        Column,
        RowDense,
        ColumnDense,
    }

    internal enum TaffyEdge : uint
    {
        Top,
        Bottom,
        Left,
        Right,
        Vertical,
        Horizontal,
        All,
    }

    internal enum TaffyUnit : uint
    {
        None,
        Length,
        Percent,
        MinContent,
        MaxContent,
        FitContentPx,
        FitContentPercent,
        Auto,
        Fr,
    }

    internal enum TaffyMeasureMode : uint
    {
        Exact,
        FitContent,
        MinContent,
        MaxContent,
    }


}
